
//Account Actions
export const RETRIEVE_USER_STATUS = "RETRIEVE_USER_STATUS"
export const USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED"

export const LOGIN_DATA = "LOGIN_DATA"
export const LOGIN_FAILED = "LOGIN_FAILED"